(async () => {
  'use strict';
  if (document.readyState === 'loading') await new Promise(resolve => document.addEventListener('DOMContentLoaded', resolve, {once:true}));
  if (window.numenCatalogReady) await window.numenCatalogReady;
  const form=document.querySelector('#bookingForm'),message=document.querySelector('#bookingMessage');
  if(!form||!message)return;
  const base=window.NUMEN_CONFIG?.studioApiBase;
  if(base){form.action=base+'/inquiries';const label=document.createElement('label');label.className='booking-agreement-label';const input=document.createElement('input');input.type='checkbox';input.name='reminderConsent';input.value='yes';label.append(input,document.createTextNode(' Email me an appointment reminder if my visit is confirmed.'));form.querySelector('.booking-agreement').append(label);}
  let draft=null;try{draft=JSON.parse(sessionStorage.getItem('numen.inquiry-draft.v1'))}catch{}
  if(draft&&typeof draft.message==='string'&&window.NumenNails?.normalizeDesign(draft.design)){
    const banner=document.createElement('div');banner.className='atelier-draft-banner';const copy=document.createElement('p');copy.textContent='Your atelier design is ready below. Review your idea, add your contact details, and send when you’re ready.';const link=document.createElement('a');link.href='studio.html#design';link.textContent='Return to your design ↗';const remove=document.createElement('button');remove.type='button';remove.textContent='Remove atelier draft';remove.style.display='block';banner.append(copy,link,remove);form.prepend(banner);
    message.value=draft.message.slice(0,700);message.dispatchEvent(new Event('input',{bubbles:true}));const select=document.querySelector('#bookingService');if([...select.options].some(o=>o.value===draft.service))select.value=draft.service;
    // Metadata is never trusted by the server; it is a requested design, not a quote.
    const meta=document.createElement('input');meta.type='hidden';meta.name='studioDraft';meta.value=JSON.stringify({design:window.NumenNails.normalizeDesign(draft.design),slotId:draft.slotId||null,date:draft.date||'',time:draft.time||'',silent:!!draft.silent});form.append(meta);
    const image=document.createElement('canvas');image.width=1000;image.height=690;window.NumenNails.renderSet(image,draft.design);let removed=false;
    image.toBlob(blob=>{if(removed||!blob||typeof DataTransfer==='undefined')return;const transfer=new DataTransfer(),input=document.querySelector('#visionPhotos');transfer.items.add(new File([blob],'my-numen-nail-design.jpg',{type:'image/jpeg'}));input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}))},'image/jpeg',.9);
    remove.addEventListener('click',()=>{removed=true;try{sessionStorage.removeItem('numen.inquiry-draft.v1')}catch{}if(message.value===draft.message.slice(0,700))message.value='';message.dispatchEvent(new Event('input',{bubbles:true}));meta.remove();const input=document.querySelector('#visionPhotos');if(typeof DataTransfer!=='undefined'){const transfer=new DataTransfer();for(const file of input.files)if(file.name!=='my-numen-nail-design.jpg')transfer.items.add(file);input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}))}banner.remove()});
  }
  document.addEventListener('numen:inquiry-sent',()=>{try{sessionStorage.removeItem('numen.inquiry-draft.v1')}catch{}document.querySelector('.atelier-draft-banner')?.remove();form.querySelector('[name=studioDraft]')?.remove();if(matchMedia('(prefers-reduced-motion:reduce)').matches||window.numenMotion?.paused)return;const celebration=document.createElement('div');celebration.className='inquiry-magic-celebration';celebration.setAttribute('aria-hidden','true');const img=document.createElement('img');img.src='assets/img/fairy-sprite.webp';img.alt='';const text=document.createElement('p');text.textContent='A little wish, sent.';celebration.append(img,text);document.body.append(celebration);setTimeout(()=>celebration.remove(),2600)});
  try{let season=JSON.parse(localStorage.getItem('numen.season'));if(season==='auto'){const m=new Date().getMonth();season=m<2||m===11?'winter':m<5?'spring':m<8?'summer':'autumn'}if(['moonlight','spring','summer','autumn','winter','haunted'].includes(season))document.body.dataset.season=season}catch{}
})();
