(() => {
  'use strict';const $=id=>document.getElementById(id),canvas=$('brandCanvas'),ctx=canvas.getContext('2d'),sets=window.NUMEN_STUDIO_DEFAULTS.collections;let image=null,loadVersion=0;
  const palettes={moonlight:['#211c29','#eee5db','#d7bd8b','#c4a0ce'],petal:['#4b2639','#f6e7e5','#d4aa9b','#e8b5c9'],ocean:['#18343d','#edf0e7','#bcd9d1','#8bb7c4']};
  const dimensions={post:[1080,1080],story:[1080,1920],card:[1050,600],care:[1200,1800],label:[1200,900]};
  function fitText(text,max,font,min=18){let size=font;while(size>min){ctx.font=`${size}px Atelier, Georgia`;if(ctx.measureText(text).width<=max)break;size--}return size}
  function wrap(text,x,y,max,line,align='center'){ctx.textAlign=align;const words=text.split(' ');let row='';for(const word of words){const next=row?row+' '+word:word;if(ctx.measureText(next).width>max&&row){ctx.fillText(row,x,y);row=word;y+=line}else row=next}if(row)ctx.fillText(row,x,y);return y+line}
  function moon(x,y,r,p){ctx.fillStyle=p[2];ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.fillStyle=p[0];ctx.beginPath();ctx.arc(x+r*.45,y-r*.2,r*.86,0,Math.PI*2);ctx.fill();ctx.fillStyle=p[2];ctx.font=`${r*.65}px Georgia`;ctx.textAlign='center';ctx.fillText('✦',x+r*.85,y+r*.6)}
  function cover(img,x,y,w,h){const r=Math.min(w/img.width,h/img.height),nw=img.width*r,nh=img.height*r;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.drawImage(img,x+(w-nw)/2,y+(h-nh)/2,nw,nh);ctx.restore()}
  function draw(){const type=$('brandFormat').value,p=palettes[$('brandPalette').value],w=dimensions[type][0],h=dimensions[type][1],set=sets[Number($('brandCollection').value)||0];canvas.width=w;canvas.height=h;ctx.fillStyle=p[0];ctx.fillRect(0,0,w,h);ctx.strokeStyle=p[2]+'77';ctx.lineWidth=1.5;ctx.strokeRect(w*.035,w*.035,w*.93,h-w*.07);ctx.textAlign='center';const headline=$('brandHeadline').value.trim()||'A little magic, made yours.',sub=$('brandSubline').value.trim();
    if(type==='post'||type==='story') {const story=type==='story';moon(w*.5,h*(story?.08:.07),w*.025,p);ctx.fillStyle=p[1];ctx.font=`${w*.056}px Atelier, Georgia`;ctx.fillText('Numen Nails',w*.5,h*(story?.15:.15));if(image)cover(image,w*.075,h*(story?.21:.21),w*.85,h*(story?.45:.48));ctx.fillStyle=p[2];ctx.font=`${w*.016}px Nunito, Arial`;ctx.fillText('THE COLLECTION CHRONICLES',w*.5,h*(story?.715:.755));ctx.fillStyle=p[1];ctx.font=`${fitText(set.title,w*.86,w*.068)}px Atelier, Georgia`;ctx.fillText(set.title,w*.5,h*(story?.77:.825));ctx.fillStyle=p[3];ctx.font=`${w*.027}px Atelier, Georgia`;wrap(headline,w*.5,h*(story?.82:.88),w*.8,w*.035);ctx.fillStyle=p[1];ctx.font=`${w*.017}px Nunito, Arial`;ctx.fillText('numennails.com',w*.5,h*.955);if(story){ctx.font=`${w*.019}px Nunito, Arial`;ctx.fillStyle=p[3];wrap(sub,w*.5,h*.875,w*.72,w*.03)}}
    else if(type==='card'){moon(w*.18,h*.4,w*.046,p);ctx.fillStyle=p[1];ctx.font=`${w*.086}px Atelier, Georgia`;ctx.textAlign='left';ctx.fillText('Numen Nails',w*.3,h*.42);ctx.fillStyle=p[3];ctx.font=`${w*.027}px Atelier, Georgia`;wrap(headline,w*.3,h*.54,w*.62,w*.035,'left');ctx.strokeStyle=p[2]+'77';ctx.beginPath();ctx.moveTo(w*.09,h*.69);ctx.lineTo(w*.91,h*.69);ctx.stroke();ctx.fillStyle=p[1];ctx.font=`${w*.019}px Nunito, Arial`;ctx.textAlign='left';ctx.fillText('numennails.com',w*.09,h*.83);ctx.font=`${w*.013}px Nunito, Arial`;ctx.textAlign='right';ctx.fillText('CUSTOM NAIL ART & PRESS-ONS',w*.91,h*.83)}
    else if(type==='label'){moon(w*.5,h*.19,w*.04,p);ctx.fillStyle=p[1];ctx.font=`${w*.093}px Atelier, Georgia`;ctx.fillText('Numen Nails',w*.5,h*.42);ctx.fillStyle=p[3];ctx.font=`${w*.044}px Atelier, Georgia`;wrap(headline,w*.5,h*.56,w*.8,w*.055);ctx.fillStyle=p[2];ctx.font=`${w*.02}px Nunito, Arial`;wrap(sub,w*.5,h*.72,w*.78,w*.03);ctx.fillStyle=p[1];ctx.font=`${w*.02}px Nunito, Arial`;ctx.fillText('numennails.com',w*.5,h*.9)}
    else {moon(w*.5,h*.09,w*.035,p);ctx.fillStyle=p[1];ctx.font=`${w*.07}px Atelier, Georgia`;ctx.fillText('Keep the magic.',w*.5,h*.19);ctx.fillStyle=p[3];ctx.font=`${w*.025}px Nunito, Arial`;ctx.fillText('A LITTLE CARE GOES A LONG WAY',w*.5,h*.24);let y=h*.34;const items=[['Treat them gently.','Use your fingertips, not your nails, to open, peel, and lift.'],['Protect your set.','Wear gloves for cleaning and avoid picking at edges or embellishments.'],['Keep care simple.','Keep hands clean and dry. Follow the aftercare instructions provided with your service.'],['Remove with care.','Never force, bite, or pull off your set. Follow your adhesive instructions or ask your nail artist.'],['Stay in touch.','For a repair, removal, or a little advice about your set, contact Numen Nails.']];items.forEach(([t,body],i)=>{ctx.fillStyle=p[2];ctx.textAlign='left';ctx.font=`${w*.022}px Nunito, Arial`;ctx.fillText('0'+(i+1),w*.1,y);ctx.fillStyle=p[1];ctx.font=`${w*.041}px Atelier, Georgia`;ctx.fillText(t,w*.19,y);ctx.fillStyle=p[3];ctx.font=`${w*.022}px Nunito, Arial`;const end=wrap(body,w*.19,y+w*.04,w*.7,w*.035,'left');y=end+w*.08});ctx.textAlign='center';ctx.fillStyle=p[1];ctx.font=`${w*.022}px Nunito, Arial`;ctx.fillText('Numen Nails · numennails.com',w*.5,h*.95)}
    $('brandSizeNote').textContent={post:'A 1080 × 1080 PNG, ready for your social feed.',story:'A 1080 × 1920 PNG for stories.',card:'3.5 × 2 inches at 300 pixels per inch. For professional bleed and trim marks, use the print PDF.',care:'4 × 6 inches at 300 pixels per inch. Follow product-specific aftercare instructions.',label:'4 × 3 inches at 300 pixels per inch. A flat label design for your packaging.'}[type];
  }
  async function choosePhoto(){const version=++loadVersion;image=null;draw();const set=sets[Number($('brandCollection').value)||0],im=new Image();im.src=set.photos[0].src;try{await im.decode();if(version!==loadVersion)return;image=im;draw()}catch{if(version===loadVersion){$('brandStatus').textContent='The collection photo could not load. Please try another set.';$('brandStatus').classList.add('visible')}}}
  sets.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.title;$('brandCollection').append(o)});$('brandCollection').addEventListener('change',choosePhoto);['brandFormat','brandPalette'].forEach(id=>$(id).addEventListener('change',draw));['brandHeadline','brandSubline'].forEach(id=>$(id).addEventListener('input',draw));$('downloadBrand').addEventListener('click',()=>{canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='numen-nails-'+$('brandFormat').value+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')});
  $('brandCollection').value='2';document.fonts.ready.then(choosePhoto);window.NumenBrand={draw};
})();
