(() => {
  'use strict';const $=id=>document.getElementById(id),base=window.NUMEN_CONFIG?.studioApiBase||'';let state=null,preview=false,collectionIndex=0,currentRequest=null,toastTimer,busy=false;
  function toast(message,error=false){$('ownerToast').textContent=message;$('ownerToast').classList.toggle('status-error',error);$('ownerToast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('ownerToast').classList.remove('visible'),5000)}
  async function api(path,options={}){const result=await fetch(base+path,{credentials:'same-origin',...options,headers:{Accept:'application/json',...(options.body instanceof Blob?{}:options.body?{'Content-Type':'application/json'}:{}),'X-Numen-Admin':'1',...options.headers},signal:AbortSignal.timeout(15000)});const type=result.headers.get('content-type')||'';if(!type.includes('application/json'))throw Error('Your owner session needs sign-in. Refresh and sign in again.');const data=await result.json();if(!result.ok)throw Error(data.message||'The request could not be completed.');return data}
  function gate(title,copy,signIn=false){$('ownerGate').hidden=false;$('ownerWorkspace').hidden=true;$('ownerGateTitle').textContent=title;$('ownerGateCopy').textContent=copy;$('previewOwner').hidden=false;$('ownerSignIn').hidden=!signIn;if(signIn)$('ownerSignIn').href=base+'/admin/login'}
  async function load(){if(!base){gate('Your owner desk is ready for setup.','The public atelier works now. Shared client records, uploads, and scheduling need the private hosting service connected. You can preview the workspace and export catalog drafts below.');return}try{state=await api('/admin/state');preview=false;renderAll()}catch(e){gate('Sign in to your owner desk.',e.message,true)}}
  $('previewOwner').addEventListener('click',()=>{preview=true;state={settings:{...structuredClone(window.NUMEN_STUDIO_DEFAULTS),cashAppUrl:''},version:0,inquiries:[],slots:[],owner:'Workspace preview',remindersEnabled:false};renderAll()});
  function renderAll(){$('ownerGate').hidden=true;$('ownerWorkspace').hidden=false;$('ownerIdentity').textContent=preview?'Workspace preview · no private data':state.owner;$('ownerNotice').textContent=preview?'Preview mode. Catalog edits and openings stay in this tab. Exporting a draft downloads a file; it does not publish changes. Client records and photo uploads need the private service.':'Your private owner session is active. Review changes before publishing.';$('ownerLogout').hidden=preview;$('saveCollections').textContent=preview?'Export catalog draft ↓':'Publish catalog';$('savePrices').textContent=preview?'Export price draft ↓':'Publish prices';$('collectionUpload').disabled=preview;$('uploadHelp').textContent=preview?'Photo uploads become available after the private service is connected. Existing photos can be described, rotated, and reordered here.':'JPG, PNG or WebP · 4 MB each · up to 12 photos per set.';$('reminderState').textContent=state.remindersEnabled?'Automatic email reminders are enabled for confirmed appointments when the client opted in.':'Automatic reminders are off. They need the connected email service and scheduled job to be enabled.';renderRequests();renderSlots();renderCollections();renderPrices();route()}
  function empty(root,text){const p=document.createElement('p');p.className='empty-state';p.textContent=text;root.append(p)}
  const dateText=value=>new Date(value).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})+' ET';
  function cards(root,rows){root.replaceChildren();if(!rows.length){empty(root,preview?'No sample clients. Real requests will appear here after the private service is connected.':'No matching requests yet.');return}rows.forEach(row=>{const a=document.createElement('article');a.className='request-card';const status=document.createElement('span'),h=document.createElement('h3'),meta=document.createElement('p'),copy=document.createElement('p'),button=document.createElement('button');status.className='status-pill';status.dataset.status=row.status;status.textContent=row.status.replaceAll('_',' ');h.textContent=row.name;meta.textContent=row.service+' · '+dateText(row.created_at);copy.textContent=row.message.slice(0,150)+(row.message.length>150?'…':'');button.type='button';button.className='quiet-button';button.textContent='Open request ↗';button.addEventListener('click',()=>openRequest(row));a.append(status,h,meta,copy,button);root.append(a)})}
  function renderRequests(){$('requestCount').textContent=state.inquiries.filter(r=>r.status==='new').length;const filter=$('statusFilter').value;cards($('requestList'),state.inquiries.filter(r=>filter==='all'||r.status===filter))}
  $('statusFilter').addEventListener('change',renderRequests);$('refreshOwner').addEventListener('click',()=>{if(preview)return toast('This is a preview. No live requests are connected.');load()});
  function openRequest(row){currentRequest=row;$('requestTitle').textContent=row.name;$('requestMeta').textContent=`${row.email} · ${row.service} · ${dateText(row.created_at)}${row.silent?' · Silent appointment requested':''}`;$('requestMessage').textContent=row.message;$('requestStatus').value=row.status;$('requestNotes').value=row.notes||'';$('requestDeposit').checked=!!row.deposit_received;$('requestSlot').replaceChildren();const none=document.createElement('option');none.value='';none.textContent='Choose an opening';$('requestSlot').append(none);state.slots.filter(s=>s.state==='open'||s.inquiry_id===row.id).forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=dateText(s.starts_at)+(s.id===row.requested_slot_id?' · client preference':'');$('requestSlot').append(o)});$('requestSlot').value=row.slot_id||row.requested_slot_id||'';$('requestPhotos').replaceChildren();for(const photo of row.photos||[]){if(!/^inquiries\/[a-f0-9-]+\/[a-f0-9-]+\.(jpg|png|webp)$/.test(photo.key))continue;const a=document.createElement('a'),im=document.createElement('img');a.href=base+'/admin/photo/'+photo.key.replace('inquiries/','');a.target='_blank';a.rel='noopener';im.src=a.href;im.alt=photo.name||'Client reference';a.append(im);$('requestPhotos').append(a)}$('replyClient').href='mailto:'+encodeURIComponent(row.email)+'?subject='+encodeURIComponent('Your Numen Nails inquiry');$('downloadAppointment').hidden=!row.appointment_start;$('requestDialog').showModal()}
  $('requestDialog').querySelector('.dialog-close').addEventListener('click',()=>$('requestDialog').close());
  $('requestForm').addEventListener('submit',async e=>{e.preventDefault();if(preview||busy||!currentRequest)return;busy=true;const button=e.submitter;button.disabled=true;try{await api('/admin/inquiries/'+currentRequest.id,{method:'PUT',body:JSON.stringify({revision:currentRequest.revision,status:$('requestStatus').value,notes:$('requestNotes').value,depositReceived:$('requestDeposit').checked,slotId:$('requestSlot').value||null})});$('requestDialog').close();await load();toast('Request updated. Reply to your client with any appointment changes.')}catch(error){toast(error.message,true)}finally{busy=false;button.disabled=false}});
  function downloadText(content,name,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  $('downloadAppointment').addEventListener('click',()=>{const r=currentRequest;if(!r?.appointment_start)return;const slot=state.slots.find(s=>s.id===r.slot_id),start=new Date(r.appointment_start),end=slot?new Date(slot.ends_at):new Date(start.getTime()+3*3600000),stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Numen Nails//Atelier//EN','BEGIN:VEVENT','UID:'+r.id+'@numennails.com','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(start),'DTEND:'+stamp(end),'SUMMARY:Numen Nails appointment','DESCRIPTION:See your artist for confirmed location and appointment details.','STATUS:CONFIRMED','END:VEVENT','END:VCALENDAR',''].join('\r\n');downloadText(body,'numen-nails-appointment.ics','text/calendar')});
  function renderSlots(){const root=$('slotList');root.replaceChildren();if(!state.slots.length){empty(root,'No openings published yet. Add the times you want clients to request.');return}state.slots.forEach(s=>{const row=document.createElement('div');row.className='slot-row';const p=document.createElement('p'),small=document.createElement('small');p.textContent=dateText(s.starts_at);small.textContent=`${Math.round((Date.parse(s.ends_at)-Date.parse(s.starts_at))/3600000*10)/10} hours · ${s.state}`;p.append(small);row.append(p);if(s.state==='open'){const b=document.createElement('button');b.type='button';b.textContent='Remove';b.addEventListener('click',async()=>{b.disabled=true;try{if(preview){state.slots=state.slots.filter(x=>x.id!==s.id);renderSlots()}else{await api('/admin/slots/'+s.id,{method:'DELETE'});await load()}}catch(e){toast(e.message,true);b.disabled=false}});row.append(b)}root.append(row)})}
  function easternISO(value){const [date,time]=value.split('T'),[y,m,d]=date.split('-').map(Number),[hh,mm]=time.split(':').map(Number);const target=Date.UTC(y,m-1,d,hh,mm);let guess=target;const parts=ts=>Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).formatToParts(ts).map(p=>[p.type,p.value]));for(let i=0;i<3;i++){const p=parts(guess),represented=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute);guess+=target-represented}const p=parts(guess);if(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`!==value)throw Error('That time does not exist in Eastern time because of the clock change.');return new Date(guess).toISOString()}
  $('slotForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;try{const start=easternISO($('slotStart').value),end=new Date(Date.parse(start)+Number($('slotDuration').value)*3600000).toISOString();if(Date.parse(start)<=Date.now())throw Error('Choose a future time.');if(preview){if(state.slots.some(s=>s.starts_at<end&&s.ends_at>start))throw Error('This time overlaps another opening.');state.slots.push({id:crypto.randomUUID(),starts_at:start,ends_at:end,state:'open'});state.slots.sort((a,b)=>a.starts_at.localeCompare(b.starts_at));renderSlots();toast('Preview opening added in this tab. Nothing was published.')}else{busy=true;e.submitter.disabled=true;await api('/admin/slots',{method:'POST',body:JSON.stringify({starts_at:start,ends_at:end})});await load();toast('Opening published.')}e.target.reset()}catch(error){toast(error.message,true)}finally{busy=false;e.submitter.disabled=false}});
  function captureCollection(){const c=state.settings.collections[collectionIndex];if(!c)return;c.title=$('collectionTitle').value.trim();c.description=$('collectionDescription').value.trim();c.service=$('collectionService').value.trim();c.world=$('collectionWorld').value;}
  function renderCollections(){const list=$('collectionList');list.replaceChildren();state.settings.collections.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-pressed',String(i===collectionIndex));const im=document.createElement('img');if(c.photos[0])im.src=c.photos[0].src;im.alt='';const span=document.createElement('span');span.textContent=c.title||'New collection';if(c.photos[0])b.append(im);b.append(span);b.addEventListener('click',()=>{captureCollection();collectionIndex=i;renderCollections()});list.append(b)});if(collectionIndex>=state.settings.collections.length)collectionIndex=0;const c=state.settings.collections[collectionIndex];$('collectionId').value=c.id;$('collectionTitle').value=c.title;$('collectionDescription').value=c.description;$('collectionService').value=c.service;$('collectionWorld').value=c.world;renderPhotos()}
  function renderPhotos(){const c=state.settings.collections[collectionIndex];$('collectionPhotos').replaceChildren();c.photos.forEach((photo,i)=>{const card=document.createElement('div');card.className='owner-photo';const img=document.createElement('img');img.src=photo.src;img.alt=photo.alt;img.style.transform=photo.rotation?`rotate(${photo.rotation}deg) scale(.75)`:'';const label=document.createElement('label');label.textContent='Photo description';const input=document.createElement('input');input.type='text';input.maxLength=300;input.value=photo.alt;input.addEventListener('input',()=>photo.alt=input.value);label.append(input);const controls=document.createElement('div');controls.className='action-group';for(const [text,action] of [['←',()=>{if(i){[c.photos[i-1],c.photos[i]]=[c.photos[i],c.photos[i-1]];renderPhotos()}}],['↻',()=>{photo.rotation=photo.rotation===0?90:photo.rotation===90?180:photo.rotation===180?-90:0;renderPhotos()}],['Remove',()=>{c.photos.splice(i,1);renderPhotos()}]]){const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label',text==='←'?'Move photo earlier':text==='↻'?'Rotate photo clockwise':'Remove photo');b.addEventListener('click',action);controls.append(b)}card.append(img,label,controls);$('collectionPhotos').append(card)})}
  $('collectionForm').addEventListener('submit',e=>{e.preventDefault();captureCollection();renderCollections();toast('Collection draft updated. Publish the catalog when ready.')});
  $('addCollection').addEventListener('click',()=>{captureCollection();state.settings.collections.unshift({id:'set-'+crypto.randomUUID(),title:'',description:'',service:'Custom nail art',world:'forest',photos:[]});collectionIndex=0;renderCollections();$('collectionTitle').focus()});
  $('removeCollection').addEventListener('click',()=>{if(state.settings.collections.length<=1)return toast('Keep at least one collection.',true);const removed=state.settings.collections.splice(collectionIndex,1)[0];collectionIndex=0;renderCollections();toast((removed.title||'Collection')+' removed from this draft. Reload to discard unpublished changes.')});
  $('collectionUpload').addEventListener('change',async e=>{if(preview)return;captureCollection();const files=[...e.target.files],c=state.settings.collections[collectionIndex];if(c.photos.length+files.length>12)return toast('Use no more than 12 photos in one set.',true);e.target.disabled=true;try{for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>4*1024*1024)throw Error('Every photo must be JPG, PNG or WebP under 4 MB.');const result=await api('/admin/photos',{method:'POST',body:file,headers:{'Content-Type':file.type}});c.photos.push({src:result.src,alt:c.title||'Nail design',rotation:0});renderPhotos()}toast('Photos added to this draft. Publish the catalog when ready.')}catch(error){toast(error.message,true)}finally{e.target.value='';e.target.disabled=false}});
  const lengthLabels=['Short','Medium','Long','XL','XXL'];
  function renderPrices(){$('ownerPriceFields').replaceChildren();for(const [key,title] of [['full','Full set'],['fill','Fill'],['pressons','Press-ons'],['extras','Art & extras'],['care','Gel & care']]){const section=document.createElement('div');section.className='owner-price-group';const h=document.createElement('h3');h.textContent=title;section.append(h);const list=['full','fill','pressons'].includes(key)?lengthLabels.map((label,i)=>[key+'.'+i,label]):key==='extras'?[['art','Nail art'],['gems','Gems'],['ombre','Ombré'],['stickers','Stickers'],['threeD','3D art'],['chrome','Chrome'],['catEye','Cat eye']]:[['gel','Basic gel'],['frenchGel','French gel'],['removal','Removal']];for(const [id,label] of list){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.type='number';input.min='0';input.max='2000';input.step='.5';input.required=true;input.dataset.price=id;const [k,i]=id.split('.');input.value=i===undefined?state.settings.prices[k]:state.settings.prices[k][+i];l.append(input);section.append(l)}$('ownerPriceFields').append(section)}$('ownerCashApp').value=state.settings.cashAppUrl||''}
  function capturePrices(){if(!$('pricesForm').reportValidity())return false;document.querySelectorAll('[data-price]').forEach(input=>{const [k,i]=input.dataset.price.split('.');if(i===undefined)state.settings.prices[k]=Number(input.value);else state.settings.prices[k][+i]=Number(input.value)});const link=$('ownerCashApp').value.trim();if(link&&!/^https:\/\/cash\.app\/\$[a-z0-9_]{1,40}$/i.test(link)){toast('Use a Cash App profile URL beginning https://cash.app/$.',true);return false}state.settings.cashAppUrl=link;return true}
  async function saveCatalog(){if(busy)return;captureCollection();if(!capturePrices())return;if(state.settings.collections.some(c=>!c.title||!c.photos.length))return toast('Each collection needs a name and at least one photo.',true);if(preview){downloadText(JSON.stringify({settings:state.settings,previewOpenings:state.slots},null,2),'numen-nails-catalog-draft.json','application/json');return toast('Draft downloaded. Your live site has not changed.')}busy=true;$('saveCollections').disabled=$('savePrices').disabled=true;try{const data=await api('/admin/catalog',{method:'PUT',body:JSON.stringify({settings:state.settings,version:state.version})});state.version=data.version;toast('Catalog and prices published to the atelier.')}catch(e){toast(e.message,true)}finally{busy=false;$('saveCollections').disabled=$('savePrices').disabled=false}}
  $('saveCollections').addEventListener('click',saveCatalog);$('savePrices').addEventListener('click',saveCatalog);$('pricesForm').addEventListener('submit',e=>{e.preventDefault();saveCatalog()});
  $('clientSearchForm').addEventListener('submit',async e=>{e.preventDefault();if(preview)return toast('Client history requires the connected private service.');e.submitter.disabled=true;try{const data=await api('/admin/clients?email='+encodeURIComponent($('clientEmail').value.trim().toLowerCase()));cards($('clientHistory'),data.inquiries)}catch(error){toast(error.message,true)}finally{e.submitter.disabled=false}});
  function route(){if(!state)return;const requested=location.hash.slice(1),tab=['requests','calendar','collections','prices','clients'].includes(requested)?requested:'requests';document.querySelectorAll('.owner-panel').forEach(p=>p.hidden=p.id!=='owner-'+tab);document.querySelectorAll('[data-owner-tab]').forEach(a=>{if(a.dataset.ownerTab===tab)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')})}
  addEventListener('hashchange',route);load();
})();
