(() => {
  'use strict';
  const $=id=>document.getElementById(id), N=window.NumenNails, defaults=window.NUMEN_STUDIO_DEFAULTS;
  if(!N||!defaults)return;
  const lengths=['Short','Medium','Long','XL','XXL'];
  const worlds={forest:{name:'Moonlit daydream',copy:'Earthy little details, soft lavender, and a touch of woodland wonder.',colors:['#c8a2d1','#83b9ae','#ecdac6']},blossom:{name:'A blossom kind of soul',copy:'Petal-soft color and delicate details, with room for something beautifully unexpected.',colors:['#e8bbc5','#702d4b','#ecdac6']},midnight:{name:'Midnight muse',copy:'Dark romance, bold contrast, and details that deserve a second look.',colors:['#261d2d','#702d4b','#c8a2d1']},ocean:{name:'A little ocean magic',copy:'Cool blue, sea-glass shimmer, and a quiet kind of confidence.',colors:['#647bab','#83b9ae','#e8e6e2']},starlight:{name:'Written in the stars',copy:'A little drama, a little shimmer, and all the space to shine.',colors:['#d5bd7c','#c8a2d1','#e8bbc5']}};
  let catalog=structuredClone(defaults),selected=0,panel='',toastTimer,bookIndex=0,bookPhoto=0,handImage=null,handUrl=null,overlayIndex=0,quizStep=0,quizAnswers=[],quizWorld='forest',slots=[];
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
  const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
  let design=N.normalizeDesign(read('numen.design.v1',null))||{shape:'almond',type:'full',length:1,mirror:true,inspiration:'',nails:N.colors.slice(0,5).map((c,i)=>({color:i===2?'#ecdac6':i===3?'#e8bbc5':'#c8a2d1',finish:'gloss',charm:i===3?'star':'none',strokes:[]}))};
  const model=new N.NailModel($('nail3d'),()=>{$('previewLabel').textContent='Design preview';$('nail3d').setAttribute('aria-label','Nail design preview');document.querySelector('.preview-top .tiny-label').textContent='Your selected nail';document.querySelector('.view-controls').hidden=true;});
  function toast(text){$('studioToast').textContent=text;$('studioToast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('studioToast').classList.remove('visible'),4200)}
  function download(canvas,name){canvas.toBlob(blob=>{if(!blob)return toast('Your image could not be created. Please try again.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')}
  function summary(){const t={full:'Full set',pressons:'Custom press-ons',fill:'Fill'}[design.type];return `${t}; ${lengths[design.length]} ${design.shape}. ${design.nails.map((n,i)=>`${N.fingers[i]}: ${n.color}, ${n.finish}${n.charm!=='none'?', '+n.charm:''}${n.strokes.length?', painted details':''}`).join('; ')}. ${design.mirror?'Mirror on the other hand.':'Other hand to be discussed.'}${design.inspiration?' Inspired by '+design.inspiration+'.':''}`}
  function estimate(){const p=catalog.prices;let total=p[design.type][design.length];design.nails.forEach(n=>{let add=0;if(n.finish==='chrome')add+=p.chrome;if(n.finish==='aura')add+=p.ombre;if(n.strokes.length)add+=p.art;if(n.charm==='gem')add+=p.gems;if(['star','moon'].includes(n.charm))add+=p.stickers;if(n.charm==='flower')add+=p.threeD;total+=add*(design.mirror?2:1)});return total}
  function persist(){write('numen.design.v1',design)}
  function update(){
    const n=design.nails[selected];$('setType').value=design.type;$('nailLength').value=String(design.length);$('mirrorSet').checked=design.mirror;$('customColor').value=n.color;$('activeFingerLabel').textContent=N.fingers[selected];
    for(const [attr,val] of [['shape',design.shape],['finish',n.finish],['charm',n.charm],['color',n.color]])document.querySelectorAll(`[data-${attr}]`).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[attr]===val)));
    document.querySelectorAll('[data-finger]').forEach((b,i)=>{b.setAttribute('aria-pressed',String(i===selected));N.renderNail(b.querySelector('canvas'),design.nails[i],design.shape)});
    model.update(n,design.shape,design.length);N.renderNail($('paintCanvas'),n,design.shape);$('paintCanvas').setAttribute('aria-label',`Draw on the ${N.fingers[selected].toLowerCase()} nail`);
    $('priceEstimate').textContent='$'+estimate();$('priceExplanation').textContent='Based on the listed base price and selected art, chrome, and details. Final quote confirmed personally.';
    N.renderSet($('bookingPreview'),design);$('bookingDesignSummary').textContent=`${lengths[design.length]} ${design.shape} · ${design.type==='pressons'?'custom press-ons':design.type==='fill'?'fill':'full set'} · starting estimate $${estimate()}`;
    if(handImage)renderTryon();persist();
  }
  N.fingers.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.dataset.finger=i;b.setAttribute('aria-label',`Customize ${name.toLowerCase()} nail`);b.setAttribute('aria-pressed',String(i===0));const c=document.createElement('canvas');c.width=120;c.height=200;c.setAttribute('aria-hidden','true');b.append(c,document.createTextNode(name));b.addEventListener('click',()=>{selected=i;update()});$('fingerPicker').append(b)});
  N.colors.forEach((color,i)=>{const b=document.createElement('button');b.type='button';b.dataset.color=color;b.style.background=color;b.className='color-swatch';b.title=color;b.setAttribute('aria-label',['Lavender','Petal pink','Warm nude','Burgundy','Midnight','Ocean blue','Sea glass','Champagne','Pearl'][i]);b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{design.nails[selected].color=color;update()});$('colorSwatches').append(b)});
  for(const attr of ['shape','finish','charm'])document.querySelectorAll(`[data-${attr}]`).forEach(b=>b.addEventListener('click',()=>{if(attr==='shape')design.shape=b.dataset.shape;else design.nails[selected][attr]=b.dataset[attr];update()}));
  $('customColor').addEventListener('input',e=>{design.nails[selected].color=e.target.value;update()});$('setType').addEventListener('change',e=>{design.type=e.target.value;update()});$('nailLength').addEventListener('change',e=>{design.length=Number(e.target.value);update()});$('mirrorSet').addEventListener('change',e=>{design.mirror=e.target.checked;update()});
  $('applyAll').addEventListener('click',()=>{design.nails=design.nails.map(()=>structuredClone(design.nails[selected]));update();toast('This look is now on all five nails.')});
  $('rotateLeft').addEventListener('click',()=>model.rotate(-.3));$('rotateRight').addEventListener('click',()=>model.rotate(.3));$('resetView').addEventListener('click',()=>model.reset());
  // Drawings are normalized vectors, so they survive changing preview sizes.
  let stroke=null;const pc=$('paintCanvas');const point=(e,c)=>{const r=c.getBoundingClientRect();return[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]};
  pc.addEventListener('pointerdown',e=>{if(design.nails[selected].strokes.length>=100)return toast('This nail has reached 100 strokes. Undo or clear some to keep painting.');pc.setPointerCapture(e.pointerId);stroke={color:$('brushColor').value,size:Number($('brushSize').value),points:[point(e,pc)]};design.nails[selected].strokes.push(stroke);N.renderNail(pc,design.nails[selected],design.shape)});
  pc.addEventListener('pointermove',e=>{if(!stroke||stroke.points.length>=700)return;stroke.points.push(point(e,pc).map(v=>Math.max(0,Math.min(1,v))));N.renderNail(pc,design.nails[selected],design.shape)});
  const finishStroke=()=>{if(stroke){stroke=null;update()}};pc.addEventListener('pointerup',finishStroke);pc.addEventListener('pointercancel',finishStroke);
  $('undoPaint').addEventListener('click',()=>{design.nails[selected].strokes.pop();update()});$('clearPaint').addEventListener('click',()=>{design.nails[selected].strokes=[];update()});
  function saved(){const a=read('numen.saved.v1',[]);return(Array.isArray(a)?a:[]).filter(d=>N.normalizeDesign(d.design)).slice(0,12)}
  function renderSaved(){const all=saved();$('savedCount').textContent=all.length;$('savedDesigns').replaceChildren();all.forEach((item,i)=>{const box=document.createElement('article');box.className='saved-card';const c=document.createElement('canvas');c.width=450;c.height=310;N.renderSet(c,N.normalizeDesign(item.design));const h=document.createElement('h4');h.textContent=item.name;const load=document.createElement('button');load.type='button';load.textContent='Open design';load.addEventListener('click',()=>{design=N.normalizeDesign(item.design);update();toast('Saved design opened.');$('designTitle').scrollIntoView({block:'start',behavior:paused?'instant':'smooth'})});const remove=document.createElement('button');remove.type='button';remove.textContent='Delete';remove.setAttribute('aria-label','Delete '+item.name);remove.addEventListener('click',()=>{const list=saved();list.splice(i,1);write('numen.saved.v1',list);renderSaved()});box.append(c,h,load,remove);$('savedDesigns').append(box)})}
  $('saveDesign').addEventListener('click',()=>{const all=saved();if(all.length>=12)return toast('Your shelf holds 12 designs. Download or remove one to make room.');all.unshift({name:`${lengths[design.length]} ${design.shape} · ${new Date().toLocaleDateString()}`,design:structuredClone(design)});if(!write('numen.saved.v1',all))return toast('Browser storage is full. Download your design image instead.');renderSaved();toast('Saved to your design shelf on this device.')});
  $('downloadDesign').addEventListener('click',()=>{const c=document.createElement('canvas');c.width=1600;c.height=1100;N.renderSet(c,design);download(c,'numen-nails-my-dream-set.png')});$('useDesign').addEventListener('click',()=>location.hash='booking');

  // Local photo mockup: no image upload, server request, or storage of the hand.
  let overlays=[];function resetOverlays(){const c=$('tryonCanvas');overlays=N.fingers.map((_,i)=>({x:c.width*(.2+i*.15),y:c.height*(.3+Math.abs(2-i)*.06),w:c.width*.065,h:c.width*.11,angle:0,opacity:.92}));overlayIndex=0;syncOverlay()}
  function syncOverlay(){const o=overlays[overlayIndex];if(!o)return;$('overlayFinger').value=overlayIndex;for(const [id,val] of [['overlayWidth',o.w],['overlayHeight',o.h],['overlayAngle',o.angle],['overlayOpacity',o.opacity*100]])$(id).value=val;}
  function renderTryon(){if(!handImage)return;const c=$('tryonCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(handImage,0,0,c.width,c.height);overlays.forEach((o,i)=>{const nail=document.createElement('canvas');nail.width=240;nail.height=420;N.renderNail(nail,design.nails[i],design.shape);ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.angle*Math.PI/180);ctx.globalAlpha=o.opacity;ctx.drawImage(nail,-o.w/2,-o.h/2,o.w,o.h);ctx.restore()});}
  $('handPhoto').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>12*1024*1024){toast('Choose a JPG, PNG or WebP under 12 MB.');e.target.value='';return}const url=URL.createObjectURL(f);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>40e6)throw Error();if(handUrl)URL.revokeObjectURL(handUrl);handUrl=url;handImage=img;const scale=Math.min(1,960/img.naturalWidth,1200/img.naturalHeight);$('tryonCanvas').width=Math.round(img.naturalWidth*scale);$('tryonCanvas').height=Math.round(img.naturalHeight*scale);$('tryonEmpty').hidden=true;$('tryonCanvas').hidden=false;['downloadTryon','replacePhoto','removePhoto'].forEach(id=>$(id).disabled=false);resetOverlays();renderTryon();toast('Your photo stays here. Drag each nail into place.')}catch{URL.revokeObjectURL(url);toast('This photo could not be opened. Try a smaller JPG or PNG.')}finally{e.target.value=''}});
  $('replacePhoto').addEventListener('click',()=>$('handPhoto').click());$('removePhoto').addEventListener('click',()=>{handImage=null;if(handUrl)URL.revokeObjectURL(handUrl);handUrl=null;const c=$('tryonCanvas');c.getContext('2d').clearRect(0,0,c.width,c.height);c.hidden=true;$('tryonEmpty').hidden=false;['downloadTryon','replacePhoto','removePhoto'].forEach(id=>$(id).disabled=true);toast('Your hand photo has been removed.')});
  $('downloadTryon').addEventListener('click',()=>download($('tryonCanvas'),'numen-nails-hand-mockup.png'));$('overlayFinger').addEventListener('change',e=>{overlayIndex=Number(e.target.value);syncOverlay()});
  for(const [id,key,mult] of [['overlayWidth','w',1],['overlayHeight','h',1],['overlayAngle','angle',1],['overlayOpacity','opacity',.01]])$(id).addEventListener('input',e=>{if(!handImage)return;overlays[overlayIndex][key]=Number(e.target.value)*mult;renderTryon()});
  const moveOverlay=(dx,dy)=>{const o=overlays[overlayIndex],c=$('tryonCanvas');if(!o)return;o.x=Math.max(0,Math.min(c.width,o.x+dx));o.y=Math.max(0,Math.min(c.height,o.y+dy));renderTryon()};
  document.querySelectorAll('[data-nudge]').forEach(b=>b.addEventListener('click',()=>moveOverlay(...b.dataset.nudge.split(',').map(Number))));
  let dragOffset=null;const tc=$('tryonCanvas');tc.addEventListener('pointerdown',e=>{if(!handImage)return;const p=point(e,tc).map((v,i)=>v*(i?tc.height:tc.width));let hit=-1;for(let i=overlays.length-1;i>=0;i--){const o=overlays[i],dx=p[0]-o.x,dy=p[1]-o.y,a=-o.angle*Math.PI/180,x=dx*Math.cos(a)-dy*Math.sin(a),y=dx*Math.sin(a)+dy*Math.cos(a);if(Math.abs(x)<=o.w*.5&&Math.abs(y)<=o.h*.5){hit=i;break}}if(hit<0)return;overlayIndex=hit;syncOverlay();dragOffset=[p[0]-overlays[hit].x,p[1]-overlays[hit].y];tc.setPointerCapture(e.pointerId)});
  tc.addEventListener('pointermove',e=>{if(!dragOffset)return;const p=point(e,tc);const o=overlays[overlayIndex];o.x=Math.max(0,Math.min(tc.width,p[0]*tc.width-dragOffset[0]));o.y=Math.max(0,Math.min(tc.height,p[1]*tc.height-dragOffset[1]));renderTryon()});tc.addEventListener('pointerup',()=>dragOffset=null);tc.addEventListener('pointercancel',()=>dragOffset=null);tc.addEventListener('keydown',e=>{const d={ArrowLeft:[-3,0],ArrowRight:[3,0],ArrowUp:[0,-3],ArrowDown:[0,3]}[e.key];if(d){e.preventDefault();moveOverlay(...d)}});

  function renderBook(){const set=catalog.collections[bookIndex];if(!set)return;const photo=set.photos[bookPhoto];$('bookPhoto').src=photo.src;$('bookPhoto').alt=photo.alt;$('bookPhoto').style.transform=photo.rotation?`rotate(${photo.rotation}deg) scale(.75)`:'';$('bookPhotoCount').textContent=`Photo ${bookPhoto+1} of ${set.photos.length}`;$('bookPhotoPrev').disabled=$('bookPhotoNext').disabled=set.photos.length<2;$('bookTitle').textContent=set.title;$('bookDescription').textContent=set.description;$('bookWorld').textContent=set.service+' · '+(worlds[set.world]?.name||'Nail art');$('bookPage').textContent=`${String(bookIndex+1).padStart(2,'0')} / ${String(catalog.collections.length).padStart(2,'0')}`;$('bookJump').value=set.id;$('bookPalette').replaceChildren();(worlds[set.world]||worlds.forest).colors.forEach(color=>{const s=document.createElement('span');s.style.background=color;s.title=color;$('bookPalette').append(s)})}
  function turnBook(delta){bookIndex=(bookIndex+delta+catalog.collections.length)%catalog.collections.length;bookPhoto=0;$('storybook').classList.remove('turning');void $('storybook').offsetWidth;$('storybook').classList.add('turning');renderBook()}
  function fillBookJump(){$('bookJump').replaceChildren();catalog.collections.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.title;$('bookJump').append(o)});renderBook()}
  $('bookPrev').addEventListener('click',()=>turnBook(-1));$('bookNext').addEventListener('click',()=>turnBook(1));$('bookJump').addEventListener('change',e=>{bookIndex=catalog.collections.findIndex(s=>s.id===e.target.value);bookPhoto=0;renderBook()});
  for(const [id,d] of [['bookPhotoPrev',-1],['bookPhotoNext',1]])$(id).addEventListener('click',()=>{const total=catalog.collections[bookIndex].photos.length;bookPhoto=(bookPhoto+d+total)%total;renderBook()});
  function inspire(world,title){const mood=worlds[world]||worlds.forest;design.nails=design.nails.map((_,i)=>({color:mood.colors[i%3],finish:i===2?'glitter':'gloss',charm:i===3?(world==='blossom'?'flower':world==='midnight'?'moon':'star'):'none',strokes:[]}));design.inspiration=title;update();location.hash='design';toast('A fresh concept inspired by '+title+'.')}
  $('bookInspire').addEventListener('click',()=>{const s=catalog.collections[bookIndex];inspire(s.world,s.title)});
  const questions=[{title:'Where does your imagination wander?',options:[['A moonlit garden','Quiet paths & little wonders','forest'],['A blossom-filled afternoon','Soft petals & romantic details','blossom'],['Beside an endless ocean','Cool colors & a calm shimmer','ocean']]},{title:'How do you like to make an entrance?',options:[['Softly, but memorably','Delicate, personal, lovely','blossom'],['A little mysterious','Dark details & bold contrast','midnight'],['Like I belong among the stars','Sparkle, confidence & a little drama','starlight']]},{title:'Choose your finishing touch.',options:[['Something that blooms','Flowers, texture & tiny details','blossom'],['Something with an edge','Graphic lines & dark romance','midnight'],['Something that catches the light','Chrome, shimmer & celestial accents','starlight']]}];
  function renderQuiz(){const q=questions[quizStep];$('quizStep').textContent=`0${quizStep+1} / 03`;$('quizProgressBar').style.width=`${(quizStep+1)/3*65}%`;$('quizQuestion').textContent=q.title;$('quizBack').hidden=!quizStep;$('quizOptions').replaceChildren();q.options.forEach(([title,copy,world])=>{const b=document.createElement('button');b.type='button';b.style.setProperty('--quiz-art',`url('../assets/img/${world==='forest'?'forest-distant':'realm-'+world}.webp')`);const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=title;small.textContent=copy;b.append(strong,small);b.addEventListener('click',()=>{quizAnswers[quizStep]=world;if(quizStep<2){quizStep++;renderQuiz();$('quizQuestion').tabIndex=-1;$('quizQuestion').focus()}else showQuizResult()});$('quizOptions').append(b)})}
  function showQuizResult(){const scores={};quizAnswers.forEach((w,i)=>scores[w]=(scores[w]||0)+(i===0?1.1:1));quizWorld=Object.keys(scores).sort((a,b)=>scores[b]-scores[a])[0];const w=worlds[quizWorld];$('quizResultTitle').textContent=w.name;$('quizResultCopy').textContent=w.copy;$('moodBoard').replaceChildren();const matches=[...catalog.collections].sort((a,b)=>(b.world===quizWorld)-(a.world===quizWorld)).slice(0,3);matches.forEach(set=>{const a=document.createElement('a');a.href='#storybook';const im=document.createElement('img'),h=document.createElement('h4'),p=document.createElement('p');im.src=set.photos[0].src;im.alt=set.photos[0].alt;h.textContent=set.title;p.textContent=set.service;a.append(im,h,p);a.addEventListener('click',()=>{bookIndex=catalog.collections.findIndex(s=>s.id===set.id);bookPhoto=0;renderBook()});$('moodBoard').append(a)});$('quizQuestions').hidden=true;$('quizResults').hidden=false;$('quizResultTitle').tabIndex=-1;$('quizResultTitle').focus()}
  $('quizBack').addEventListener('click',()=>{quizStep=Math.max(0,quizStep-1);renderQuiz()});$('quizRestart').addEventListener('click',()=>{quizStep=0;quizAnswers=[];$('quizQuestions').hidden=false;$('quizResults').hidden=true;renderQuiz()});$('quizUse').addEventListener('click',()=>inspire(quizWorld,worlds[quizWorld].name));

  function renderPrices(){const root=$('studioPrices');root.replaceChildren();for(const [key,title] of [['full','Full set'],['fill','Fill'],['pressons','Press-ons']]){const div=document.createElement('div'),h=document.createElement('h3'),dl=document.createElement('dl');h.textContent=title;catalog.prices[key].forEach((price,i)=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=lengths[i];dd.textContent='$'+price;row.append(dt,dd);dl.append(row)});div.append(h,dl);root.append(div)}const div=document.createElement('div'),h=document.createElement('h3');h.textContent='Art & extras';div.append(h);const dl=document.createElement('dl');for(const [key,title] of [['art','Nail art'],['gems','Gems'],['ombre','Ombré'],['stickers','Stickers'],['threeD','3D art'],['chrome','Chrome'],['catEye','Cat eye (press-ons)']]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=title;dd.textContent='$'+catalog.prices[key];row.append(dt,dd);dl.append(row)}div.append(dl);root.append(div);const gel=document.createElement('div'),gh=document.createElement('h3'),gdl=document.createElement('dl');gh.textContent='Gel & care';for(const [k,t] of [['gel','Basic gel manicure'],['frenchGel','French gel manicure'],['removal','Removal (my work only)']]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t;dd.textContent='$'+catalog.prices[k];row.append(dt,dd);gdl.append(row)}gel.append(gh,gdl);root.append(gel)}
  $('openPrices').addEventListener('click',()=>$('pricesDialog').showModal());$('pricesDialog').querySelector('.dialog-close').addEventListener('click',()=>$('pricesDialog').close());$('pricesBook').addEventListener('click',()=>$('pricesDialog').close());$('pricesDialog').addEventListener('click',e=>{if(e.target===$('pricesDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});

  // Prefer a date, never pretend a request is a confirmed appointment.
  const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());$('preferredDate').min=today.toISOString().slice(0,10);
  let chosenSlot=null;
  $('preferredDate').addEventListener('change',()=>{chosenSlot=null;document.querySelectorAll('[data-slot]').forEach(b=>b.setAttribute('aria-pressed','false'))});$('preferredTime').addEventListener('change',()=>{chosenSlot=null;document.querySelectorAll('[data-slot]').forEach(b=>b.setAttribute('aria-pressed','false'))});
  $('continueInquiry').addEventListener('click',()=>{const date=$('preferredDate');if(date.value&&!date.checkValidity()){date.reportValidity();return}let request=summary();if(chosenSlot)request+=` Preferred slot: ${new Date(chosenSlot.starts_at).toLocaleString('en-US',{timeZone:catalog.timezone})} (${catalog.timezone}).`;else if(date.value)request+=` Preferred date: ${date.value}; ${$('preferredTime').value||'flexible time'}.`;if($('silentRequest').checked)request+=' Silent appointment requested.';const draft={message:request.slice(0,700),service:design.type==='pressons'?'Custom press-ons':design.type==='fill'?'Fill':'Acrylic full set',design,slotId:chosenSlot?.id||null,date:date.value,time:$('preferredTime').value,silent:$('silentRequest').checked};try{sessionStorage.setItem('numen.inquiry-draft.v1',JSON.stringify(draft));location.href='index.html#contact'}catch{toast('Your browser could not carry the design over. Download it and attach it to your inquiry.')}});

  const hints={salon:'Tap the cabinet, vanity, or spellbook. Three tiny discoveries are tucked around the room.',design:'Each little nail is selectable. Open the art canvas below to draw your own details.',tryon:'Choose a hand photo, then drag each nail into place. It never leaves your device.',storybook:'Turn the pages to browse real work. You can use any collection as a starting point.',quiz:'Follow your first instinct. I’ll find a few real sets to inspire you.',booking:'Your idea goes into an inquiry you can review before sending. The artist confirms the visit.'};
  $('fairyGuideButton').addEventListener('click',()=>{const open=$('fairyHint').hidden;$('fairyHint').hidden=!open;$('fairyGuideButton').setAttribute('aria-expanded',String(open))});
  function route(){const hash=location.hash.slice(1).split('?')[0],next=Object.hasOwn(hints,hash)?hash:'salon';if(panel===next)return;panel=next;document.querySelectorAll('.studio-panel').forEach(s=>s.hidden=s.id!=='panel-'+panel);document.querySelectorAll('[data-panel]').forEach(a=>{if(a.dataset.panel===panel)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('fairyHint').textContent=hints[panel];if(panel==='design')model.draw();if(panel==='tryon'&&handImage)renderTryon();if(panel==='booking')update();document.title=`${{salon:'The Enchanted Atelier',design:'Create Your Dream Set',tryon:'Hand Photo Try-On',storybook:'The Collection Chronicles',quiz:'Find Your Magic',booking:'Plan a Visit'}[panel]} | Numen Nails`;document.querySelector(`[data-panel="${panel}"]`)?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'})}
  addEventListener('hashchange',route);
  let paused=read('numen.studio-paused',false)||matchMedia('(prefers-reduced-motion:reduce)').matches;
  const motionMedia=matchMedia('(prefers-reduced-motion:reduce)');function syncMotion(){document.documentElement.classList.toggle('is-studio-paused',paused||motionMedia.matches||document.hidden);$('motionButton').textContent=motionMedia.matches?'Reduced motion':paused?'Resume magic':'Pause magic';$('motionButton').setAttribute('aria-pressed',String(paused));$('motionButton').disabled=motionMedia.matches;}
  $('motionButton').addEventListener('click',()=>{paused=!paused;write('numen.studio-paused',paused);syncMotion()});motionMedia.addEventListener('change',syncMotion);document.addEventListener('visibilitychange',syncMotion);
  let found=read('numen.discoveries.v1',[]);if(!Array.isArray(found))found=[];const secretKeys=['mushroom','star','moon'];found=found.filter(x=>secretKeys.includes(x));
  function discoveryUI(){document.querySelectorAll('[data-secret]').forEach(b=>{const done=found.includes(b.dataset.secret);b.classList.toggle('found',done);b.setAttribute('aria-pressed',String(done))});$('discoveryCount').textContent=found.length===3?'The secret garden is yours. ✦':`${found.length} of 3 little secrets discovered.`}
  document.querySelectorAll('[data-secret]').forEach(b=>b.addEventListener('click',()=>{if(found.includes(b.dataset.secret))return toast('You’ve already found this little secret.');found.push(b.dataset.secret);write('numen.discoveries.v1',found);discoveryUI();if(found.length===3){toast('You found the secret garden. A woodland design is waiting at the vanity.');design.inspiration='The secret fairy garden';design.nails=design.nails.map((_,i)=>({color:['#83b9ae','#c8a2d1','#ecdac6'][i%3],finish:i===2?'glitter':'gloss',charm:i===3?'flower':i===1?'moon':'none',strokes:[]}));update()}else toast({mushroom:'The mushroom wakes a little gathering of fireflies.',star:'A little starlight, just for you.',moon:'The moon has left a wish in the garden.'}[b.dataset.secret]);const field=document.querySelector('.season-particles');for(let i=0;i<8;i++){const s=document.createElement('i');s.textContent='✦';s.style.cssText=`--x:${15+Math.random()*70}%;--duration:3s;--delay:0s`;field.append(s);setTimeout(()=>s.remove(),3200)}}));
  function season(value){write('numen.season',value);let resolved=value;if(value==='auto'){const m=new Date().getMonth();resolved=m<2||m===11?'winter':m<5?'spring':m<8?'summer':'autumn'}document.body.dataset.season=resolved;const field=document.querySelector('.season-particles');field.replaceChildren();const glyph={moonlight:'✦',spring:'❀',summer:'·',autumn:'❧',winter:'❄',haunted:'✧'}[resolved]||'✦';for(let i=0;i<18;i++){const p=document.createElement('i');p.textContent=glyph;p.style.cssText=`--x:${(i*37)%100}%;--duration:${12+i%8}s;--delay:-${i*1.3}s;--size:${9+i%8}px`;field.append(p)}}
  $('seasonSelect').addEventListener('change',e=>season(e.target.value));const initialSeason=read('numen.season','moonlight');if([...$('seasonSelect').options].some(o=>o.value===initialSeason))$('seasonSelect').value=initialSeason;season($('seasonSelect').value);
  async function liveCatalog(){const base=window.NUMEN_CONFIG?.studioApiBase;if(!base)return;try{const response=await fetch(base+'/public',{signal:AbortSignal.timeout(7000)});if(!response.ok)throw Error();const data=await response.json();if(Array.isArray(data.collections)&&data.collections.length)catalog.collections=data.collections;if(data.prices)catalog.prices=data.prices;if(data.timezone)catalog.timezone=data.timezone;fillBookJump();renderPrices();update();if(typeof data.cashAppUrl==='string'&&/^https:\/\/cash\.app\/\$[a-z0-9_]+$/i.test(data.cashAppUrl)){$('depositLink').href=data.cashAppUrl;$('depositInstructions').hidden=false}slots=Array.isArray(data.slots)?data.slots:[];if(slots.length){$('availabilityNote').textContent='These are the artist’s published openings. A request is confirmed personally.';$('availableSlots').hidden=false;slots.slice(0,16).forEach(slot=>{const b=document.createElement('button');b.type='button';b.dataset.slot=slot.id;b.setAttribute('aria-pressed','false');b.textContent=new Date(slot.starts_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:catalog.timezone})+' ET';b.addEventListener('click',()=>{chosenSlot=slot;document.querySelectorAll('[data-slot]').forEach(s=>s.setAttribute('aria-pressed',String(s===b)));$('preferredDate').value='';$('preferredTime').value=''});$('availableSlots').append(b)})}}catch{/* The artist's published static prices and preferred-date inquiry remain available. */}}
  let flight=null;
  function fairyVisit(target){
    if(paused||motionMedia.matches||document.hidden||!target)return;
    flight?.cancel();document.querySelector('.fairy-flight')?.remove();
    const start=$('fairyGuideButton').getBoundingClientRect(),end=target.getBoundingClientRect();
    const x=Math.max(0,Math.min(innerWidth-130,end.right-85)),y=Math.max(0,Math.min(innerHeight-100,end.top-70));
    const fairy=document.createElement('div');fairy.className='fairy-flight';fairy.setAttribute('aria-hidden','true');
    for(const part of ['wings','body']){const img=document.createElement('img');img.src='assets/img/fairy-'+part+'.webp';img.className='guide-'+part;img.alt='';fairy.append(img)}
    document.body.append(fairy);
    flight=fairy.animate([{transform:`translate(${start.left}px,${start.top}px)`,opacity:0},{transform:`translate(${(start.left+x)/2}px,${Math.min(start.top,y)-55}px)`,opacity:1,offset:.3},{transform:`translate(${x}px,${y}px) rotate(-5deg)`,opacity:1,offset:.6},{transform:`translate(${start.left}px,${start.top}px)`,opacity:0}],{duration:2300,easing:'ease-in-out'});
    flight.onfinish=()=>fairy.remove();flight.oncancel=()=>fairy.remove();
  }
  document.addEventListener('click',event=>{const target=event.target.closest('#saveDesign,#quizUse,[data-secret],.salon-hotspot,[data-charm]');if(target)fairyVisit(target)});
  $('motionButton').addEventListener('click',()=>{if(paused)flight?.cancel()});
  document.querySelector('.guide-body').addEventListener('error',event=>{event.target.src='assets/img/fairy-sprite.webp';document.querySelector('#fairyGuideButton .guide-wings').hidden=true},{once:true});
  update();renderSaved();fillBookJump();renderQuiz();renderPrices();discoveryUI();syncMotion();route();liveCatalog();
})();
