import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handle,sendReminders} from '../studio-api/worker.mjs';
import {verifyOwner} from '../studio-api/auth.mjs';
import {validateSettings,imageSignature} from '../studio-api/validation.mjs';
import defaults from '../data/studio-defaults.json' with {type:'json'};
const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk=await crypto.subtle.exportKey('jwk',pair.publicKey);jwk.kid='test-key';
const b64=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v)).toString('base64url');
async function token(overrides={}){const t=Math.floor(Date.now()/1000),head=b64({alg:'RS256',kid:'test-key'}),body=b64({iss:'https://test-numen.cloudflareaccess.com',aud:['numen-owner'],email:'owner@example.test',iat:t,exp:t+3600,...overrides}),unsigned=head+'.'+body;return unsigned+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(unsigned))).toString('base64url')}
const validToken=await token();let sent=[];
globalThis.fetch=async(url,options={})=>{const target=String(url);if(target.endsWith('/cdn-cgi/access/certs'))return Response.json({keys:[jwk]});if(target.includes('/turnstile/'))return Response.json({success:true});if(target==='https://api.resend.com/emails'){sent.push(JSON.parse(options.body));return Response.json({id:'test-email'})}if(target.includes('/moderations'))return Response.json({results:[{flagged:false}]});throw Error('Unexpected network call '+target)};
class DB{constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(readFileSync(new URL('../studio-api/migrations/0001_studio.sql',import.meta.url),'utf8'))}prepare(sql){const db=this.db;let args=[];return {bind(...values){args=values;return this},runSync(){const r=db.prepare(sql).run(...args);return {success:true,meta:{changes:Number(r.changes)}}},async run(){return this.runSync()},async all(){return {results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)||null}}}async batch(list){this.db.exec('BEGIN');try{const out=list.map(s=>s.runSync());this.db.exec('COMMIT');return out}catch(e){this.db.exec('ROLLBACK');throw e}}}
const env=()=>({SITE_ORIGIN:'https://numennails.com',ACCESS_TEAM_DOMAIN:'test-numen.cloudflareaccess.com',ACCESS_AUD:'numen-owner',ADMIN_EMAILS:'owner@example.test',DB:new DB(),MEDIA:{get:async()=>null,put:async()=>{}},INQUIRY_RATE_LIMIT:{get:async()=>null,put:async()=>{}},TURNSTILE_SECRET_KEY:'test-only',RESEND_API_KEY:'test-only',INQUIRY_FROM_EMAIL:'test@example.test',INQUIRY_TO_EMAIL:'owner@example.test'});
const req=(path,{method='GET',body,auth=validToken,origin='https://numennails.com',extra={}}={})=>new Request('https://numennails.com/api/studio'+path,{method,headers:{...(auth?{'Cf-Access-Jwt-Assertion':auth}:{}),Origin:origin,'X-Numen-Admin':'1',...(body?{'Content-Type':'application/json'}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})});
function inquiry(e,id,email='client@example.test'){const now=new Date().toISOString();e.DB.db.prepare('INSERT INTO inquiries (id,created_at,updated_at,name,email,service,message,revision) VALUES (?,?,?,?,?,?,?,?)').run(id,now,now,'Test client',email,'Custom nail art','A test design',id+'-revision')}
function slot(e,id,start=Date.now()+86400000){e.DB.db.prepare('INSERT INTO slots (id,starts_at,ends_at) VALUES (?,?,?)').run(id,new Date(start).toISOString(),new Date(start+3*3600000).toISOString())}
test('owner access rejects missing, forged, expired, wrong-audience, and non-owner tokens',async()=>{const e=env();for(const tok of [null,'invalid.jwt.signature',await token({exp:1}),await token({aud:['other-app']}),await token({email:'stranger@example.test'})]){assert.equal(await verifyOwner(req('/admin/state',{auth:tok}),e),null);assert.equal((await handle(req('/admin/state',{auth:tok}),e)).status,401)}assert.equal((await verifyOwner(req('/admin/state'),e)).email,'owner@example.test')});
test('owner writes require same-origin and CSRF header; unconfigured service fails closed',async()=>{const e=env();assert.equal((await handle(req('/admin/catalog',{method:'PUT',body:{},origin:'https://evil.test'}),e)).status,403);assert.equal((await handle(req('/admin/catalog',{method:'PUT',body:{},extra:{'X-Numen-Admin':''}}),e)).status,403);assert.equal((await handle(req('/admin/state'),{SITE_ORIGIN:e.SITE_ORIGIN})).status,503)});
test('public catalog never contains client data; private photo paths require owner auth',async()=>{const e=env();inquiry(e,'aaaaaaaa-1111');slot(e,'bbbbbbbb-2222');const response=await handle(req('/public',{auth:null}),e),body=await response.text();assert.equal(response.status,200);assert.ok(!body.includes('client@example.test'));assert.ok(!body.includes('inquiries'));assert.equal((await handle(req('/admin/photo/aaaaaaaa-1111/cccccc.jpg',{auth:null}),e)).status,401);assert.equal((await handle(req('/media/../inquiries/aaa.jpg',{auth:null}),e)).status,404)});
test('catalog publishing enforces versions and rejects external or executable image paths',async()=>{const e=env(),settings={...structuredClone(defaults),cashAppUrl:''};assert.equal((await handle(req('/admin/catalog',{method:'PUT',body:{settings,version:0}}),e)).status,200);assert.equal((await handle(req('/admin/catalog',{method:'PUT',body:{settings,version:0}}),e)).status,409);settings.collections[0].photos[0].src='javascript:alert(1)';assert.throws(()=>validateSettings(settings));assert.equal((await handle(req('/admin/catalog',{method:'PUT',body:{settings,version:1}}),e)).status,400)});
test('two requests cannot reserve the same opening and stale edits cannot overwrite a reservation',async()=>{const e=env(),a='aaaaaaaa-1111',b='bbbbbbbb-2222',sid='cccccccc-3333';inquiry(e,a);inquiry(e,b);slot(e,sid);const update=id=>handle(req('/admin/inquiries/'+id,{method:'PUT',body:{revision:id+'-revision',status:'confirmed',slotId:sid,notes:'',depositReceived:true}}),e);const results=await Promise.all([update(a),update(b)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal(e.DB.db.prepare("SELECT COUNT(*) AS n FROM inquiries WHERE status='confirmed'").get().n,1);assert.equal((await update(a)).status,409);const row=e.DB.db.prepare('SELECT * FROM inquiries WHERE id=?').get(a);assert.equal((await handle(req('/admin/inquiries/'+a,{method:'PUT',body:{revision:row.revision,status:'cancelled',slotId:null}}),e)).status,200);assert.equal(e.DB.db.prepare('SELECT state FROM slots WHERE id=?').get(sid).state,'open')});
test('overlapping openings and completion of an unconfirmed request are rejected',async()=>{const e=env(),id='aaaaaaaa-1111';inquiry(e,id);const starts_at=new Date(Date.now()+48*3600000).toISOString(),ends_at=new Date(Date.now()+51*3600000).toISOString();assert.equal((await handle(req('/admin/slots',{method:'POST',body:{starts_at,ends_at}}),e)).status,200);assert.equal((await handle(req('/admin/slots',{method:'POST',body:{starts_at,ends_at}}),e)).status,409);assert.equal((await handle(req('/admin/inquiries/'+id,{method:'PUT',body:{revision:id+'-revision',status:'completed',slotId:'bbbbbbbb-1111'}}),e)).status,400)});
test('image upload rejects SVG and forged signatures',async()=>{const e=env();assert.equal(imageSignature(new Uint8Array([0,1,2]),'image/png'),false);const upload=new Request(e.SITE_ORIGIN+'/api/studio/admin/photos',{method:'POST',headers:{Origin:e.SITE_ORIGIN,'X-Numen-Admin':'1','Cf-Access-Jwt-Assertion':validToken,'Content-Type':'image/svg+xml'},body:'<svg onload="alert(1)"/>'});assert.equal((await handle(upload,e)).status,400)});
test('inquiries require policies, store only after delivery, and never auto-confirm',async()=>{const e=env();const make=accepted=>{const form=new FormData();for(const [key,val] of Object.entries({name:'Client',email:'client@example.test',service:'Custom nail art',message:'Lavender stars',startedAt:String(Date.now()-5000),'cf-turnstile-response':'test-response',policyAgreement:accepted?'accepted':'',reminderConsent:'yes'}))form.set(key,val);return new Request(e.SITE_ORIGIN+'/api/studio/inquiries',{method:'POST',headers:{Origin:e.SITE_ORIGIN},body:form})};assert.equal((await handle(make(false),e)).status,400);assert.equal((await handle(make(true),e)).status,200);const row=e.DB.db.prepare('SELECT * FROM inquiries').get();assert.equal(row.status,'new');assert.equal(row.reminder_consent,1);assert.equal(row.email,'client@example.test');assert.equal(row.appointment_start,null)});
test('reminders are disabled by default, require client consent, and are not sent twice',async()=>{const e=env(),id='aaaaaaaa-1111';inquiry(e,id);e.DB.db.prepare("UPDATE inquiries SET status='confirmed',appointment_start=?,reminder_consent=1 WHERE id=?").run(new Date(Date.now()+2*3600000).toISOString(),id);sent=[];assert.deepEqual(await sendReminders(e),{sent:0});e.REMINDERS_ENABLED='true';assert.deepEqual(await sendReminders(e),{sent:1});assert.deepEqual(await sendReminders(e),{sent:0});assert.equal(sent.length,1);assert.ok(sent[0].text.includes('Eastern'));});
